UPDATE SEQUENCE SET SEQ_COUNT = SEQ_COUNT + 1 WHERE SEQ_NAME = 'SEQ_GEN';
INSERT INTO TEMPLATECLASS (ID, NAME, VERSION) VALUES((SELECT SEQ_COUNT FROM SEQUENCE WHERE SEQ_NAME = 'SEQ_GEN'), 'JPA', '1.0.0');
UPDATE SEQUENCE SET SEQ_COUNT = SEQ_COUNT + 1 WHERE SEQ_NAME = 'SEQ_GEN';
INSERT INTO TEMPLATECLASS (ID, NAME, VERSION) VALUES ((SELECT SEQ_COUNT FROM SEQUENCE WHERE SEQ_NAME = 'SEQ_GEN'), 'EclipseLink', '1.0.0');
