UPDATE SEQUENCE SET SEQ_COUNT = SEQ_COUNT + 1 WHERE SEQ_NAME = 'SEQ_GEN';
SET @newid = SELECT SEQ_COUNT FROM SEQUENCE WHERE SEQ_NAME = 'SEQ_GEN';
INSERT INTO TEMPLATECLASS (ID, NAME, VERSION) VALUES (@newid, 'JPA', '1.0.0');
UPDATE SEQUENCE SET SEQ_COUNT = SEQ_COUNT + 1 WHERE SEQ_NAME = 'SEQ_GEN';
SET @newid = SELECT SEQ_COUNT FROM SEQUENCE WHERE SEQ_NAME = 'SEQ_GEN';
INSERT INTO TEMPLATECLASS (ID, NAME, VERSION) VALUES (@newid, 'EclipseLink', '1.0.0');
