CREATE TABLE SEQUENCE (SEQ_NAME VARCHAR(50) NOT NULL, SEQ_COUNT NUMERIC(38), PRIMARY KEY (SEQ_NAME))
INSERT INTO SEQUENCE (SEQ_NAME, SEQ_COUNT) values ('SEQ_GEN', 0)

CREATE TABLE DEVICE (ID INTEGER NOT NULL, BRAND VARCHAR, MODEL VARCHAR, PRIMARY KEY (ID))
CREATE TABLE SUBSCRIPTION (ID INTEGER NOT NULL, BILLING VARCHAR, DEVICE_ID INTEGER, PRIMARY KEY (ID))
