UPDATE SEQUENCE SET SEQ_COUNT = SEQ_COUNT + 1 WHERE SEQ_NAME = 'SEQ_GEN';
SET @idValue = SELECT SEQ_COUNT FROM SEQUENCE WHERE SEQ_NAME = 'SEQ_GEN';
INSERT INTO TEMPLATECLASS (ID, NAME, TEMPLATEVERSION, VERSION) VALUES(@idValue, 'JPA', '1.0.0', 1);
